apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ include "fiaas-deploy-daemon.labels" . | nindent 4 }}
    {{ include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.deployment.labels | indent 4 }}
{{- if or .Values.annotations.global .Values.deployment.annotations }}
  annotations:
    {{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.annotations.global | indent 4 }}
    {{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{ include "fiaas-deploy-daemon.labels" . | nindent 8 }}
        {{ include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.deployment.pod.labels | indent 8 }}
{{- if or .Values.annotations.global .Values.deployment.pod.annotations }}
      annotations:
        {{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.annotations.global | indent 8 }}
        {{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.deployment.pod.annotations | indent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          env:
            - name: FIAAS_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: FIAAS_VERSION
              value: "{{ .Values.image.tag }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
