apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistedIPs }}"
{{- if .Values.ingress.enableLego }}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
{{- if .Values.ingress.enableTLS }}
{{- end }}
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.fqdn }}"
    secretName: "{{ .Values.ingress.fqdn }}"
  rules:
  - host: "{{ .Values.ingress.fqdn }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Values.name }}"
          servicePort: 5000
        path: /
