reviewersRaffle:
  strategies:
    - default:
        type: knowledge
        excludedParticipants:
          - oliver-soell
          - espen-krogh-moe
          - giao-the-cung
          - audun-fauchald-strand
