language: finnbuild
script:
  - run_finnbuild
after_failure:
  - reports-publisher
after_success:
  - reports-publisher
notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis
env:
  global:
    - FINN_GITHUB_USER=captainfiaas
    - S3_BUCKET_URL="https://s3-eu-west-1.amazonaws.com/fiaas-release.delivery-pro.schibsted.io"
    - S3_BUCKET_USERNAME="delivery"
    - secure: "H/3i2rvnUVI6en61BNBrAYhal1AAuJ351czsHKRukkfNPuxAcjS8RGXSdk7IeWGQ1I2iIAlbMM+CYk8TWlLFgl0znZmMNaCjmR3cRWfLPNLzntS6qYgzyiun407/Ix3NieZlWcpfzwPDjDLuGzhHerjZAkT5UYlqPqSie4E6X8VWKcVs3FvY+Krj2BQfIhc1q36CtKMax8Gt4Aat5+IHjQWBKqE7icqXeNuPEjJHUEt3YAXIE4MXU9BGkOAZ6Uv16YW/qHpt0aHPmqEIR6dYWu/5vio/XMl9ViaGDAsgVZKeAzE7THFbjE8ThoO4sF5Pf5H2SnKWCBdbmVjRMsnWYt0cKwcYsyKdFtFoYK4I1ZQCTNQmOeXgfgAkW73vrF9v4oFG533au+kLHkvjJG3LNs49kBARDewtD1ZWUzTby5MTNX9g260Ejut3HZrFyPMfogJxCGSDYYVa+ookuFwYtzCDRCLpeKnyaGwgDzHiJPbIeLcU+WAbFeYbAFArtcXuIF3COzewaE/lOsEnVuV/cNRdKEcdrtvUTC4FKfS59UzDeERX+nz5RMajnAkeUlqjQIQNAcTECM9JPsxUjZjidnStQqgGkCZdnnnGCN4GhRJh1rudPGNSnAzuwtjIzMVi7PIjLbKJlcBODux1UNZr+A8csLfeT0lEu7VqqSaIhQI=" # FINN_GITHUB_PWD
    - secure: "j6ddJYz0WSlPR8Dm/Aveu34H6dhDFUCZY8kIZ3Bx3vVCTKUAnUye6XNqUPKzOylwezFGE6GRGCb9Ap14F/zxzoIIs7NNfv/tA6kG1HAcoodDqgD7jDBdsn3JSubcyOL8Mj0V7w3f9bbi//cI51UXwyigh/Zqgy98N8GCEjGcTt0t+wkS3xY3nIq1bY0yC/0M4AxvEDvWSRUfuL08u2sJmtOgSUm5S9QigaiHRD7spC4dAdOFzZQkAhkoPjChndTdi7gPPvAa5ikV6/ioU8WaehJgGzUwu6c/gjo3A1Vv7DXRGXvIapn/Y/z3+dPuJDh/9vpTeGg/ilDJrTJ1wDllypD+/xXBMNcZeaPwzWT/2AJ37Q4D4IVjZ5KrtiD4h6ggEuoY9MavEL52bpfwiEi/9NHx83BHCsp0hCwnJKkT4fQtsit2iSPfleviO4+EHJY/puQhD6K31w9agR4MrG2Q2BuzpAna9+DZZnoKdZ3kIylOloWbT5TnP47cczn+HfYNkljJA/HQPJ8soba9OkPu8+zDdLgMwuZy9BDiZqTUyQP2WFR5CHfSKrGnSE0Tnp6vKgV/wRHDZeD4np8ttNAULO/XLyjXy1+pDNhftwUatvTZ84u4XXeR3yoyvjKGyBX9JAliYxg5QxdK41RtrcQ/aoDzIF6/IxVCpNaiMcm8IDg=" # S3_BUCKET_PASSWORD
