language: finnbuild
script:
  - run_finnbuild
deploy:
  provider: script
  script: bin/deploy
  skip_cleanup: true
after_failure:
  - reports-publisher

after_success:
  - reports-publisher

notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis

