language: finnbuild
script:
  - run_finnbuild
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bin/install && bin/deploy ; fi

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis
env:
  global:
    - DOCKER_IMAGE="containers.schibsted.io/finntech/fiaas-deploy-daemon"
    - HELM_VERSION="v2.5.1"
    - K8S_VERSION="1.6.2"
    - K8S_HOST="https://schip.cre-pro.schibsted.io"
    - K8S_NAMESPACE="delivery-pro"
    - secure: "FqAXYc0aXGnyphlrnoW7duKdaqVXI9zivFNWmrqe7LbRqUYEHxMY98frywLGdfSa/1oV13pykf+g5Yu0si3N+oAwvCCqYkv2Oloi9ApXeenIgPitMxXYb/aZrV8mJJI0GNkD53PNvbWs/eQMLvNfD7O61yXkXyNNmYhCy1Ha0ToW01Z6xnpVzS3Of9oPLMpNNHhIjpY7uvXTF7wKtcHfJNfM4JNb8m8lhHo5kQ8JT9GXu8HybROEYhA9mSqVSIbmPmuef827v7tJbxU723lmx//WiYeOY20uPF+6aPupPt++ebmC4FYCbr0VBNlQ2OFOeZWcCmNDwWs8HsecJXFcR/m6IbuOllm5Be6o+0Jh87fUm1Fp+CyKmB9Nlyvtjus3ZutaKDgLmcEm5wHQrDVpfjXqcBMK6K77sWLEhVdIa6QFc/jmLmIARrZfvwN/D9uFb8R2pNIEKyxxgtMBXTcTA2ZjtRpXCJvE0wEgt0QgfxZasnIatdBWFbcnAAEQ5fmvrPxPRYhaXlsn+fm6d5/+ALQB72VHRpT8aO1mzT/bRhqEZIRjYdFpNN+XfEOmNJZhgQjVrSegjXWDH6lKigTMZ3Hs80b7sfOnY50nLrd/og6SrAlq02iy4kHf1p4rTXguWc+WRFSaO4LRdq1jTYOlyXZrY43mAeDnfu0e2XpPmfk=" # K8S_TOKEN
