language: finnbuild
script:
  - run_finnbuild
after_failure:
  - reports-publisher
after_success:
  - reports-publisher
notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis
env:
  global:
    - DOCKER_IMAGE="fiaas/fiaas-deploy-daemon"
    - HELM_VERSION="v2.5.1"
    - K8S_VERSION="1.6.2"
    - K8S_HOST="https://schip.cre-pro.schibsted.io"
    - K8S_NAMESPACE="delivery-pro"
    - FINN_GITHUB_USER=captainfiaas
    - secure: "FqAXYc0aXGnyphlrnoW7duKdaqVXI9zivFNWmrqe7LbRqUYEHxMY98frywLGdfSa/1oV13pykf+g5Yu0si3N+oAwvCCqYkv2Oloi9ApXeenIgPitMxXYb/aZrV8mJJI0GNkD53PNvbWs/eQMLvNfD7O61yXkXyNNmYhCy1Ha0ToW01Z6xnpVzS3Of9oPLMpNNHhIjpY7uvXTF7wKtcHfJNfM4JNb8m8lhHo5kQ8JT9GXu8HybROEYhA9mSqVSIbmPmuef827v7tJbxU723lmx//WiYeOY20uPF+6aPupPt++ebmC4FYCbr0VBNlQ2OFOeZWcCmNDwWs8HsecJXFcR/m6IbuOllm5Be6o+0Jh87fUm1Fp+CyKmB9Nlyvtjus3ZutaKDgLmcEm5wHQrDVpfjXqcBMK6K77sWLEhVdIa6QFc/jmLmIARrZfvwN/D9uFb8R2pNIEKyxxgtMBXTcTA2ZjtRpXCJvE0wEgt0QgfxZasnIatdBWFbcnAAEQ5fmvrPxPRYhaXlsn+fm6d5/+ALQB72VHRpT8aO1mzT/bRhqEZIRjYdFpNN+XfEOmNJZhgQjVrSegjXWDH6lKigTMZ3Hs80b7sfOnY50nLrd/og6SrAlq02iy4kHf1p4rTXguWc+WRFSaO4LRdq1jTYOlyXZrY43mAeDnfu0e2XpPmfk=" # K8S_TOKEN
    - secure: "T7+wePyMisxU9hrtDpBxuAALwkBtbXNGctW21VsHo4nHE/FmPlZ5hJvZpkbi/5FtxGg24G78gunI4uJbxXb9A6l4dIRxaVxpv/WcgUDKl1Mo7nuejxw+O4Aah4sxTfzz7hvkY2NFuI2fQ69LZqJxPbuKeBC4OV7AhKi3lNO0NJKspxusHtvTxINrDWbgUNtWv/C3+T6kESBvgy+S73TJkPSwyL/SxGXBV4Adx1W5MkXi6rlzxBd05Kxq8FzIXlKKPP1ZMBFy61Helj7G0dZDBIyf7h04HxU10J61Qz1hzAd2j8fejOavcFNI9gcR+jlrNlJ/c5ZRtXUJkpjCBwlnjqRiBlk3XYi8OakIgf6wWAzXIJy/DK/lgcpZIc2ox2RtWBBN+7sAXEGa8UxGoHbn+cwDXlKQ4oszV7OYx8vBmRGC1I5rySBymbrwnfzD5SrmPEpRB5fpTUBn+tX8DUUyd6BpvpSEKU6wfIgFnxSxZcgWGVMLYMam+jyUJZG7i2B/Lft/ixHYIY/+dEAgSQ4R6kFZ/0YO6RDrayNGGFL8urJGj8xV8BjTUfBhT7A7TcBEgrmhvG3KFvK4Jg2ZKm4w+uEOezr+1YMK+kLrhhYivheyUlHR0GYgqFoYlLbs+qplbn0bFm5g7+7YvuYchm65RKn43h+s46vYahyQH+QD1Yk=" # FINN_GITHUB_PWD
