ingress:
  fqdn: fiaas-deploy-daemon.ingress.cre-pro.schibsted.io
  domainName: ingress.cre-pro.schibsted.io
  enableTLS: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    schibsted.io/heimdall: "true"
environment: pro
TPR: true
CRD: false
dataDogImage: datadog/docker-dd-agent:12.2.5172-alpine
preStopDelay: 15
