apiVersion: "schibsted.io/v1beta"
kind: PaasbetaApplication
metadata:
  name: nginx-example
  annotations:
    fiaas/artifact_id: nginx-example-1.13.0
  labels:
    fiaas/deployment_id: nginx-example-deployment-id
spec:
  application: nginx-example
  image: docker.io/nginx:1.13.0
  config:
    version: 2
    replicas: 2
    resources:
      requests:
        memory: 128m
    ports:
      - target_port: 80
    healthchecks:
      liveness:
        http:
          path: /
