name: fiaas-deploy-daemon

image:
  repository: fiaas/fiaas-deploy-daemon
  tag: latest
  pullPolicy: IfNotPresent

rbac:
  serviceAccount:
    create: true
  role:
    create: true
  roleBinding:
    create: true

labels:
  global: {}
        
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  labels: {}
  annotations: {}
  host: chart-example.local
  pathType: ImplementationSpecific

  tls:
    enabled: false
    secretName: chart-example.local

