image:
  repository: fiaas/fiaas-deploy-daemon
  tag: latest
  pullPolicy: IfNotPresent

rbac:
  serviceAccount:
    create: true
  role:
    create: true
  roleBinding:
    create: true

labels:
  global: {}
        
service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi
